{
 "title": "my dash",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU idle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])*100)",
     "legendFormat": "cpu_idle"
    }
   ]
  },
  {
   "title": "CPULA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "CPULA1" },
    { "expr": "node_load5", "legendFormat": "CPULA5" },
    { "expr": "node_load15", "legendFormat": "CPULA15" }
   ]
  },
  {
   "title": "free_ram",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "free_ram" },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "total_ram" }
   ]
  },
  {
   "title": "SSD avaible",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\", device=\"/dev/nvme0n1p2\"}",
     "legendFormat": "SSD-avaible"
    }
   ]
  }
 ]
}